services:
  repairman:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: repairman_ros2
    network_mode: "host"
    volumes:
      - ./:/workspaces/repairman_ws
    tty: true
    stdin_open: true